name: eid_celebrate
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.20
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^12.0.4
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lamp.png
    - assets/images/bg-eid.jpg
    - assets/audio/eid1.mp3
    - assets/audio/eid2.mp3
    - assets/audio/eid3.mp3
    - assets/audio/eid4.mp3
    - assets/audio/eid5.mp3
    - assets/audio/eid6.mp3
    - assets/audio/eid7.mp3
    - assets/audio/eid8.mp3
    - assets/audio/eid9.mp3
    - assets/audio/eid10.mp3
